version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      # NOTE: This is my local IP address. Change it to be yours.
      KAFKA_ADVERTISED_HOST_NAME: 10.1.2.206
      KAFKA_ZOOKEEPER_CONNECT: 10.1.2.206:2181
      KAFKA_CREATE_TOPICS: unsupervised_images:1:3,supervised_vectorized_images:1:3
      KAFKA_HEAP_OPTS: -Xmx16G -Xms16G -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=20 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
